// Generated by Code Atlas from blueprint component: Notification Service
export class NotificationService {
  constructor(private readonly eventBus: unknown) {}

  async execute(input: unknown): Promise<unknown> {
    return input;
  }
}
