// Generated by Code Atlas from blueprint component: Order Service
export class OrderService {
  constructor(private readonly ordersDB: unknown, private readonly eventBus: unknown, private readonly paymentProvider: unknown) {}

  async execute(input: unknown): Promise<unknown> {
    return input;
  }
}
