// Generated by Code Atlas from blueprint component: Web / Mobile
export class WebMobile {
  constructor(private readonly aPIGateway: unknown) {}

  async execute(input: unknown): Promise<unknown> {
    return input;
  }
}
